apiVersion: v1
kind: Service
metadata:
  name: my-service
spec:
  selector:
    app: dispatcher
  ports:
    - protocol: TCP
      port: 50051
      targetPort: 50051
      nodePort: 30163
  type: NodePort
