# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: document.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0e\x64ocument.proto\x12\x03\x64oc\"\'\n\x16\x44ocumentContentRequest\x12\r\n\x05\x64ocId\x18\x01 \x01(\x03\"8\n\x17\x44ocumentContentResponse\x12\x0f\n\x07version\x18\x01 \x01(\x05\x12\x0c\n\x04text\x18\x02 \x01(\t\"\xd6\x01\n\x0f\x44ocumentChanges\x12\r\n\x05\x64ocId\x18\x01 \x01(\x03\x12\x0f\n\x07version\x18\x02 \x01(\x05\x12,\n\x07\x64\x65letes\x18\x03 \x03(\x0b\x32\x1b.doc.DocumentChanges.Delete\x12,\n\x07inserts\x18\x04 \x03(\x0b\x32\x1b.doc.DocumentChanges.Insert\x1a\"\n\x06\x44\x65lete\x12\x0b\n\x03pos\x18\x01 \x01(\x03\x12\x0b\n\x03len\x18\x02 \x01(\x05\x1a#\n\x06Insert\x12\x0b\n\x03pos\x18\x01 \x01(\x03\x12\x0c\n\x04text\x18\x02 \x01(\t\"8\n\x16\x44ocumentChangesRequest\x12\r\n\x05\x64ocId\x18\x01 \x01(\x03\x12\x0f\n\x07version\x18\x02 \x01(\x05\"\x19\n\x17\x44ocumentChangesResponse2\x82\x02\n\x0f\x44ocumentService\x12W\n\x18GetActualDocumentContent\x12\x1b.doc.DocumentContentRequest\x1a\x1c.doc.DocumentContentResponse\"\x00\x12I\n\x12GetDocumentChanges\x12\x1b.doc.DocumentChangesRequest\x1a\x14.doc.DocumentChanges\"\x00\x12K\n\x13SendDocumentChanges\x12\x14.doc.DocumentChanges\x1a\x1c.doc.DocumentChangesResponse\"\x00\x62\x06proto3')



_DOCUMENTCONTENTREQUEST = DESCRIPTOR.message_types_by_name['DocumentContentRequest']
_DOCUMENTCONTENTRESPONSE = DESCRIPTOR.message_types_by_name['DocumentContentResponse']
_DOCUMENTCHANGES = DESCRIPTOR.message_types_by_name['DocumentChanges']
_DOCUMENTCHANGES_DELETE = _DOCUMENTCHANGES.nested_types_by_name['Delete']
_DOCUMENTCHANGES_INSERT = _DOCUMENTCHANGES.nested_types_by_name['Insert']
_DOCUMENTCHANGESREQUEST = DESCRIPTOR.message_types_by_name['DocumentChangesRequest']
_DOCUMENTCHANGESRESPONSE = DESCRIPTOR.message_types_by_name['DocumentChangesResponse']
DocumentContentRequest = _reflection.GeneratedProtocolMessageType('DocumentContentRequest', (_message.Message,), {
  'DESCRIPTOR' : _DOCUMENTCONTENTREQUEST,
  '__module__' : 'document_pb2'
  # @@protoc_insertion_point(class_scope:doc.DocumentContentRequest)
  })
_sym_db.RegisterMessage(DocumentContentRequest)

DocumentContentResponse = _reflection.GeneratedProtocolMessageType('DocumentContentResponse', (_message.Message,), {
  'DESCRIPTOR' : _DOCUMENTCONTENTRESPONSE,
  '__module__' : 'document_pb2'
  # @@protoc_insertion_point(class_scope:doc.DocumentContentResponse)
  })
_sym_db.RegisterMessage(DocumentContentResponse)

DocumentChanges = _reflection.GeneratedProtocolMessageType('DocumentChanges', (_message.Message,), {

  'Delete' : _reflection.GeneratedProtocolMessageType('Delete', (_message.Message,), {
    'DESCRIPTOR' : _DOCUMENTCHANGES_DELETE,
    '__module__' : 'document_pb2'
    # @@protoc_insertion_point(class_scope:doc.DocumentChanges.Delete)
    })
  ,

  'Insert' : _reflection.GeneratedProtocolMessageType('Insert', (_message.Message,), {
    'DESCRIPTOR' : _DOCUMENTCHANGES_INSERT,
    '__module__' : 'document_pb2'
    # @@protoc_insertion_point(class_scope:doc.DocumentChanges.Insert)
    })
  ,
  'DESCRIPTOR' : _DOCUMENTCHANGES,
  '__module__' : 'document_pb2'
  # @@protoc_insertion_point(class_scope:doc.DocumentChanges)
  })
_sym_db.RegisterMessage(DocumentChanges)
_sym_db.RegisterMessage(DocumentChanges.Delete)
_sym_db.RegisterMessage(DocumentChanges.Insert)

DocumentChangesRequest = _reflection.GeneratedProtocolMessageType('DocumentChangesRequest', (_message.Message,), {
  'DESCRIPTOR' : _DOCUMENTCHANGESREQUEST,
  '__module__' : 'document_pb2'
  # @@protoc_insertion_point(class_scope:doc.DocumentChangesRequest)
  })
_sym_db.RegisterMessage(DocumentChangesRequest)

DocumentChangesResponse = _reflection.GeneratedProtocolMessageType('DocumentChangesResponse', (_message.Message,), {
  'DESCRIPTOR' : _DOCUMENTCHANGESRESPONSE,
  '__module__' : 'document_pb2'
  # @@protoc_insertion_point(class_scope:doc.DocumentChangesResponse)
  })
_sym_db.RegisterMessage(DocumentChangesResponse)

_DOCUMENTSERVICE = DESCRIPTOR.services_by_name['DocumentService']
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _DOCUMENTCONTENTREQUEST._serialized_start=23
  _DOCUMENTCONTENTREQUEST._serialized_end=62
  _DOCUMENTCONTENTRESPONSE._serialized_start=64
  _DOCUMENTCONTENTRESPONSE._serialized_end=120
  _DOCUMENTCHANGES._serialized_start=123
  _DOCUMENTCHANGES._serialized_end=337
  _DOCUMENTCHANGES_DELETE._serialized_start=266
  _DOCUMENTCHANGES_DELETE._serialized_end=300
  _DOCUMENTCHANGES_INSERT._serialized_start=302
  _DOCUMENTCHANGES_INSERT._serialized_end=337
  _DOCUMENTCHANGESREQUEST._serialized_start=339
  _DOCUMENTCHANGESREQUEST._serialized_end=395
  _DOCUMENTCHANGESRESPONSE._serialized_start=397
  _DOCUMENTCHANGESRESPONSE._serialized_end=422
  _DOCUMENTSERVICE._serialized_start=425
  _DOCUMENTSERVICE._serialized_end=683
# @@protoc_insertion_point(module_scope)
