# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import document_content_pb2 as document__content__pb2
import storage_pb2 as storage__pb2


class StorageServiceStub(object):
    """сервис по работе с хранилищем документов
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.GetDocuments = channel.unary_stream(
                '/doc.StorageService/GetDocuments',
                request_serializer=storage__pb2.DocumentsRequest.SerializeToString,
                response_deserializer=storage__pb2.DocumentInfoResponse.FromString,
                )
        self.GetDocumentContent = channel.unary_unary(
                '/doc.StorageService/GetDocumentContent',
                request_serializer=document__content__pb2.DocumentContentRequest.SerializeToString,
                response_deserializer=document__content__pb2.DocumentContentResponse.FromString,
                )


class StorageServiceServicer(object):
    """сервис по работе с хранилищем документов
    """

    def GetDocuments(self, request, context):
        """получение списка документов
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetDocumentContent(self, request, context):
        """получение содержимого документа
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_StorageServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'GetDocuments': grpc.unary_stream_rpc_method_handler(
                    servicer.GetDocuments,
                    request_deserializer=storage__pb2.DocumentsRequest.FromString,
                    response_serializer=storage__pb2.DocumentInfoResponse.SerializeToString,
            ),
            'GetDocumentContent': grpc.unary_unary_rpc_method_handler(
                    servicer.GetDocumentContent,
                    request_deserializer=document__content__pb2.DocumentContentRequest.FromString,
                    response_serializer=document__content__pb2.DocumentContentResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'doc.StorageService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class StorageService(object):
    """сервис по работе с хранилищем документов
    """

    @staticmethod
    def GetDocuments(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(request, target, '/doc.StorageService/GetDocuments',
            storage__pb2.DocumentsRequest.SerializeToString,
            storage__pb2.DocumentInfoResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def GetDocumentContent(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/doc.StorageService/GetDocumentContent',
            document__content__pb2.DocumentContentRequest.SerializeToString,
            document__content__pb2.DocumentContentResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
