# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: storage.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import document_content_pb2 as document__content__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='storage.proto',
  package='doc',
  syntax='proto3',
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\rstorage.proto\x12\x03\x64oc\x1a\x16\x64ocument_content.proto\"\x12\n\x10\x44ocumentsRequest\"4\n\x14\x44ocumentInfoResponse\x12\r\n\x05\x64ocId\x18\x01 \x01(\x03\x12\r\n\x05title\x18\x02 \x01(\t2\xa9\x01\n\x0eStorageService\x12\x44\n\x0cGetDocuments\x12\x15.doc.DocumentsRequest\x1a\x19.doc.DocumentInfoResponse\"\x00\x30\x01\x12Q\n\x12GetDocumentContent\x12\x1b.doc.DocumentContentRequest\x1a\x1c.doc.DocumentContentResponse\"\x00\x62\x06proto3'
  ,
  dependencies=[document__content__pb2.DESCRIPTOR,])




_DOCUMENTSREQUEST = _descriptor.Descriptor(
  name='DocumentsRequest',
  full_name='doc.DocumentsRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=46,
  serialized_end=64,
)


_DOCUMENTINFORESPONSE = _descriptor.Descriptor(
  name='DocumentInfoResponse',
  full_name='doc.DocumentInfoResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='docId', full_name='doc.DocumentInfoResponse.docId', index=0,
      number=1, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='title', full_name='doc.DocumentInfoResponse.title', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=66,
  serialized_end=118,
)

DESCRIPTOR.message_types_by_name['DocumentsRequest'] = _DOCUMENTSREQUEST
DESCRIPTOR.message_types_by_name['DocumentInfoResponse'] = _DOCUMENTINFORESPONSE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

DocumentsRequest = _reflection.GeneratedProtocolMessageType('DocumentsRequest', (_message.Message,), {
  'DESCRIPTOR' : _DOCUMENTSREQUEST,
  '__module__' : 'storage_pb2'
  # @@protoc_insertion_point(class_scope:doc.DocumentsRequest)
  })
_sym_db.RegisterMessage(DocumentsRequest)

DocumentInfoResponse = _reflection.GeneratedProtocolMessageType('DocumentInfoResponse', (_message.Message,), {
  'DESCRIPTOR' : _DOCUMENTINFORESPONSE,
  '__module__' : 'storage_pb2'
  # @@protoc_insertion_point(class_scope:doc.DocumentInfoResponse)
  })
_sym_db.RegisterMessage(DocumentInfoResponse)



_STORAGESERVICE = _descriptor.ServiceDescriptor(
  name='StorageService',
  full_name='doc.StorageService',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_start=121,
  serialized_end=290,
  methods=[
  _descriptor.MethodDescriptor(
    name='GetDocuments',
    full_name='doc.StorageService.GetDocuments',
    index=0,
    containing_service=None,
    input_type=_DOCUMENTSREQUEST,
    output_type=_DOCUMENTINFORESPONSE,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
  _descriptor.MethodDescriptor(
    name='GetDocumentContent',
    full_name='doc.StorageService.GetDocumentContent',
    index=1,
    containing_service=None,
    input_type=document__content__pb2._DOCUMENTCONTENTREQUEST,
    output_type=document__content__pb2._DOCUMENTCONTENTRESPONSE,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
])
_sym_db.RegisterServiceDescriptor(_STORAGESERVICE)

DESCRIPTOR.services_by_name['StorageService'] = _STORAGESERVICE

# @@protoc_insertion_point(module_scope)
