apiVersion: apps/v1
kind: Deployment
metadata:
  name: dispatcher-deployment
  labels:
    app: trrp
spec:
  replicas: 1
  selector:
    matchLabels:
      app: dispatcher
  template:
    metadata:
      labels:
        app: dispatcher
    spec:
      containers:
      - name: dispatcher
        image: fleynaro/trrp:dispatcher-v1
        imagePullPolicy: IfNotPresent
        ports:
          - containerPort: 50051
---
apiVersion: v1
kind: Service
metadata:
  name: dispatcher-service
spec:
  selector:
    app: dispatcher
  ports:
  - name: grpc
    port: 50051
    targetPort: 50051
